services:

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - .gitignore/minio/data:/data
      - .gitignore/minio-config:/root/.minio
    networks:
      - default
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    command: server /data --console-address ":9090"
  
  spark-master:
    image: pyspark
    ports:
      - "8080:8080"
      - "7077:7077"
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./work:/usr/local/spark_dev/work
    networks:
      - default
    depends_on:
      - postgres
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
      - SPARK_LOCAL_IP=spark-master
    command: usr/local/spark/bin/spark-class org.apache.spark.deploy.master.Master --ip spark-master --port 7077 --webui-port 5050
  
  spark-worker-a:
    image: pyspark
    networks:
      - default
    depends_on:
      - spark-master
    ports:
      - "5051:5051"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
      - SPARK_LOCAL_IP=spark-worker-a
    command: usr/local/spark/bin/spark-class org.apache.spark.deploy.worker.Worker --webui-port 5051 spark://spark-master:7077
  
  spark-worker-b:
    image: pyspark
    networks:
      - default
    depends_on:
      - spark-master
    ports:
      - "5052:5052"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
      - SPARK_LOCAL_IP=spark-worker-b
    command: usr/local/spark/bin/spark-class org.apache.spark.deploy.worker.Worker --webui-port 5052 spark://spark-master:7077
  
  postgres:
    image: postgres:14.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive123
      POSTGRES_DB: metastore_db
    depends_on: 
      - minio
    volumes:
      - .gitignore/postgres/data:/var/lib/postgresql/data
    networks:
      - default

  hive-metastore:
    image: hive-metastore
    ports:
      - 9083:9083
    depends_on:
      - postgres
    restart: always
    networks:
      - default

networks:
    default:
        driver: bridge