services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - ./mount/minio/data:/data
      - ./mount/minio-config:/root/.minio
    networks:
      - default
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    command: server /data --console-address ":9090"
  postgres:
    image: postgres:14.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive123
      POSTGRES_DB: metastore_db
    depends_on: 
      - minio
    volumes:
      - ./mount/postgres/data:/var/lib/postgresql/data
    networks:
      - default
  hive-metastore:
    build: ./images/hive-metastore
    ports:
      - 9083:9083
    depends_on:
      - postgres
    restart: always
    networks:
      - default
  spark-master:
    build: ./images/spark
    ports:
      - "5050:5050"
      - "7077:7077"
    networks:
      - default
    depends_on:
      - postgres
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - SPARK_LOCAL_IP=spark-master
    command: usr/local/spark/bin/spark-class org.apache.spark.deploy.master.Master --ip spark-master --port 7077 --webui-port 5050
  spark-worker-a:
    build: ./images/spark
    networks:
      - default
    depends_on:
      - spark-master
    ports:
      - "5051:5051"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - SPARK_LOCAL_IP=spark-worker-a
    command: usr/local/spark/bin/spark-class org.apache.spark.deploy.worker.Worker --webui-port 5051 spark://spark-master:7077
  spark-worker-b:
    build: ./images/spark
    networks:
      - default
    depends_on:
      - spark-master
    ports:
      - "5052:5052"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - SPARK_LOCAL_IP=spark-worker-b
    command: usr/local/spark/bin/spark-class org.apache.spark.deploy.worker.Worker --webui-port 5052 spark://spark-master:7077
  workspace:
    build: ./images/workspace
    networks:
      - default
    depends_on:
      - spark-master
    ports:
    #  - "8080:8080"
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./work:/usr/local/spark_dev/work
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    command: jupyter notebook
  trino:
    build: ./images/trino
    networks:
      - default
    depends_on:
      - hive-metastore
    ports:
      - "8080:8080"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
networks:
    default:
        driver: bridge